import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NextTopLoader from "nextjs-toploader";

import NavigationDrawer, { NavItem } from "@/components/NavigationDrawer";
import Providers from "./providers";

import CommentIcon from "@assets/CommentIcon";
import SubjectIcon from "@assets/SubjectIcon";
import HomeIcon from "@assets/HomeIcon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "QAQ app",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Providers>
					<div className="h-screen w-screen flex flex-row">
						<NavigationDrawer>
							<NavItem title="Trang chủ" link="/" icon={HomeIcon} />
							<NavItem
								title="Bình luận"
								link="/comment/all"
								icon={CommentIcon}
								subItems={[
									{
										title: "Tất cả",
										link: "/comment/all",
									},
									{
										title: "Tích cực",
										link: "/comment/positive",
									},
									{
										title: "Tiêu cực",
										link: "/comment/negative",
									},
								]}
							/>
							<NavItem
								title="Môn học"
								link="/subject"
								icon={SubjectIcon}
								subItems={[
									{
										title: "Điểm trung bình các môn",
										link: "/subject/average-point",
									},
									{
										title: "Điểm trung bình qua các học kỳ",
										link: "/subject/point-per-year",
									},
								]}
							/>
							<NavItem
								title="Lớp học"
								link="/class"
								icon={SubjectIcon}
							/>
							<NavItem
								title="Tiêu chí"
								link="/criteria"
								icon={SubjectIcon}
							/>
						</NavigationDrawer>
						<main className="w-full px-20 pt-12 pb-10 overflow-y-scroll overflow-x-hidden">
							<NextTopLoader
								color="#2299DD"
								initialPosition={0.08}
								crawlSpeed={200}
								height={3}
								crawl={true}
								showSpinner={true}
								easing="ease"
								speed={200}
								shadow="0 0 10px #2299DD,0 0 5px #2299DD"
							/>
							{children}
						</main>
					</div>
				</Providers>
			</body>
		</html>
	);
}
