import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "./providers";
import ThemeSwitcher from "@/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Providers>
					<ThemeSwitcher />
					<div className="h-screen w-screen flex flex-row">
						<nav className="w-20 shadow-xl transition-all hover:w-96 hover:shadow-2xl"></nav>
						<main className="w-full px-20 pt-12 overflow-y-scroll overflow-x-hidden">
							{children}
						</main>
					</div>
				</Providers>
			</body>
		</html>
	);
}
