import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavigationDrawer, { NavItem } from "@/components/NavigationDrawer";
import Providers from "./providers";

import CommentIcon from "@assets/CommentIcon";
import SubjectIcon from "@assets/SubjectIcon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "QAQ app",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Providers>
					<div className="h-screen w-screen flex flex-row">
						<NavigationDrawer>
							<NavItem
								title="Bình luận"
								link="/comment/all"
								icon={CommentIcon}
								subItems={[
									{
										title: "Tất cả",
										link: "/comment/all",
									},
									{
										title: "Tích cực",
										link: "/comment/positive",
									},
									{
										title: "Tiêu cực",
										link: "/comment/negative",
									},
								]}
							/>
							<NavItem
								title="Môn học"
								link="/subject"
								icon={SubjectIcon}
								subItems={[
									{
										title: "Điểm trung bình các môn",
										link: "/subject/average-point",
									},
									{
										title: "Điểm trung bình qua các học kỳ",
										link: "/subject/point-per-year",
									},
								]}
							/>
						</NavigationDrawer>
						<main className="w-full px-20 pt-12 pb-10 overflow-y-scroll overflow-x-hidden">
							{children}
						</main>
					</div>
				</Providers>
			</body>
		</html>
	);
}
